version: "3.8"

services:
  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      # We are going to use the docker provider
      - "--providers.docker"
      # Only enabled containers should be exposed
      - "--providers.docker.exposedByDefault=false"
      # Disabling the dashbaord
      - "--api.dashboard=false"
      - "--api.insecure=false"
      # The entrypoints we want to expose
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Enable ACME (Let's Encrypt): automatic SSL.
      - "--certificatesresolvers.letsencrypt.acme.email=stortinomanfrotto@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # Global redirect to https
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    networks:
      - traefik-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json

  ################ ICECAST
  icecast:
    image: moul/icecast
    container_name: icecast-test
    restart: always
    volumes:
      - logs-test:/var/log/icecast2
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ICECAST_HOSTNAME=ice.germanaski.it
      - ICECAST_SOURCE_PASSWORD=testing
      - ICECAST_ADMIN_PASSWORD=testing
      - ICECAST_PASSWORD=testing
      - ICECAST_RELAY_PASSWORD=testing
    networks:
      - traefik-net
    ports:
      - 9090:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.icecast.rule=Host(`ice.germanaski.it`)"
      - "traefik.http.routers.icecast.entrypoints=web"
      - "traefik.http.routers.icecast-secure.tls=true"
      - "traefik.http.routers.icecast-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.icecast.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.icecast.redirectscheme.scheme=https"
      - "traefik.http.middlewares.icecast-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.icecast.middlewares=icecast-https-redirect"
      - "traefik.http.routers.icecast-secure.entrypoints=websecure"
      - "traefik.http.routers.icecast-secure.rule=Host(`ice.germanaski.it`)"
      - "traefik.docker.network=traefik-net"

volumes:
  logs-test:

networks:
  traefik-net:
