// /// <reference path="../pb_data/types.d.ts" />
// migrate(
//   (db) => {
//     const snapshot = [
//       {
//         id: "_pb_users_auth_",
//         name: "users",
//         type: "auth",
//         system: false,
//         schema: [],
//         indexes: [],
//         listRule: null,
//         viewRule: null,
//         createRule: null,
//         updateRule: null,
//         deleteRule: null,
//         options: {
//           allowEmailAuth: true,
//           allowOAuth2Auth: false,
//           allowUsernameAuth: false,
//           exceptEmailDomains: null,
//           manageRule: null,
//           minPasswordLength: 8,
//           onlyEmailDomains: null,
//           requireEmail: false,
//         },
//       },
//       {
//         id: "ymrl6gbbiznw3ii",
//         name: "nowplaying",
//         type: "base",
//         system: false,
//         schema: [
//           {
//             system: false,
//             name: "title",
//             type: "text",
//             required: true,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "artist",
//             type: "text",
//             required: true,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "url",
//             type: "text",
//             required: true,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "is_live",
//             type: "bool",
//             required: true,
//             unique: false,
//             options: {},
//           },
//         ],
//         indexes: [],
//         listRule: "",
//         viewRule: "",
//         createRule: "",
//         updateRule: "",
//         deleteRule: "",
//         options: {},
//       },
//       {
//         id: "zqs2e7bgkehjv49",
//         name: "shows",
//         type: "base",
//         system: false,
//         schema: [
//           {
//             system: false,
//             name: "title",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "author",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "description",
//             type: "editor",
//             required: false,
//             unique: false,
//             options: {},
//           },
//           {
//             system: false,
//             name: "slug",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "image",
//             type: "file",
//             required: false,
//             unique: false,
//             options: {
//               maxSelect: 1,
//               maxSize: 5242880,
//               mimeTypes: [],
//               thumbs: [],
//               protected: false,
//             },
//           },
//         ],
//         indexes: [],
//         listRule: '@request.auth.id != ""',
//         viewRule: '@request.auth.id != ""',
//         createRule: '@request.auth.id != ""',
//         updateRule: '@request.auth.id != ""',
//         deleteRule: '@request.auth.id != ""',
//         options: {},
//       },
//       {
//         name: "schedules",
//         type: "base",
//         system: false,
//         schema: [
//           {
//             system: false,
//             name: "info",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "title",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "author",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "date",
//             type: "date",
//             required: false,
//             unique: false,
//             options: {
//               min: "",
//               max: "",
//             },
//           },
//         ],
//         indexes: [],
//         listRule: '@request.auth.id != ""',
//         viewRule: '@request.auth.id != ""',
//         createRule: '@request.auth.id != ""',
//         updateRule: '@request.auth.id != ""',
//         deleteRule: '@request.auth.id != ""',
//         options: {},
//       },
//       {
//         id: "cpgulaa4gcbbzm8",
//         name: "tags",
//         type: "base",
//         system: false,
//         schema: [
//           {
//             system: false,
//             name: "tag",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//         ],
//         indexes: [],
//         listRule: '@request.auth.id != ""',
//         viewRule: '@request.auth.id != ""',
//         createRule: '@request.auth.id != ""',
//         updateRule: '@request.auth.id != ""',
//         deleteRule: '@request.auth.id != ""',
//         options: {},
//       },
//       {
//         id: "4ocj0wdpxqjifls",
//         name: "episodes",
//         type: "base",
//         system: false,
//         schema: [
//           {
//             system: false,
//             name: "title",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "author",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "date",
//             type: "date",
//             required: false,
//             unique: false,
//             options: {
//               min: "",
//               max: "",
//             },
//           },
//           {
//             system: false,
//             name: "description",
//             type: "editor",
//             required: false,
//             unique: false,
//             options: {},
//           },
//           {
//             system: false,
//             name: "slug",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "audio",
//             type: "file",
//             required: false,
//             unique: false,
//             options: {
//               maxSelect: 1,
//               maxSize: 500000000,
//               mimeTypes: [
//                 "audio/mpeg",
//                 "audio/flac",
//                 "audio/wav",
//                 "audio/aiff",
//                 "audio/aac",
//                 "audio/mp4",
//               ],
//               thumbs: [],
//               protected: false,
//             },
//           },
//           {
//             system: false,
//             name: "image",
//             type: "file",
//             required: false,
//             unique: false,
//             options: {
//               maxSelect: 1,
//               maxSize: 5242880,
//               mimeTypes: ["image/png", "image/jpeg", "image/webp"],
//               thumbs: ["300x300", "1000x1000"],
//               protected: false,
//             },
//           },
//           {
//             system: false,
//             name: "show",
//             type: "relation",
//             required: false,
//             unique: false,
//             options: {
//               collectionId: "zqs2e7bgkehjv49",
//               cascadeDelete: false,
//               minSelect: null,
//               maxSelect: 1,
//               displayFields: [],
//             },
//           },
//           {
//             system: false,
//             name: "tags",
//             type: "relation",
//             required: false,
//             unique: false,
//             options: {
//               collectionId: "cpgulaa4gcbbzm8",
//               cascadeDelete: false,
//               minSelect: null,
//               maxSelect: null,
//               displayFields: ["tag"],
//             },
//           },
//         ],
//         indexes: ["CREATE INDEX `idx_Vg36Lhg` ON `episodes` (`date`)"],
//         listRule: '@request.auth.id != ""',
//         viewRule: '@request.auth.id != ""',
//         createRule: '@request.auth.id != ""',
//         updateRule: '@request.auth.id != ""',
//         deleteRule: '@request.auth.id != ""',
//         options: {},
//       },
//       {
//         name: "playlists",
//         type: "base",
//         system: false,
//         schema: [
//           {
//             system: false,
//             name: "title",
//             type: "text",
//             required: false,
//             unique: false,
//             options: {
//               min: null,
//               max: null,
//               pattern: "",
//             },
//           },
//           {
//             system: false,
//             name: "episodes",
//             type: "relation",
//             required: false,
//             unique: false,
//             options: {
//               collectionId: "4ocj0wdpxqjifls",
//               cascadeDelete: false,
//               minSelect: null,
//               maxSelect: null,
//               displayFields: ["audio", "title", "author", "id"],
//             },
//           },
//         ],
//         indexes: [],
//         listRule: '@request.auth.id != ""',
//         viewRule: '@request.auth.id != ""',
//         createRule: '@request.auth.id != ""',
//         updateRule: '@request.auth.id != ""',
//         deleteRule: '@request.auth.id != ""',
//         options: {},
//       },
//     ];

//     const collections = snapshot.map((item) => new Collection(item));

//     return Dao(db).importCollections(collections, true, null);
//   },
//   (db) => {
//     return null;
//   }
// );
