name: Deploy
on:
  pull_request:
    branches:
      - main
jobs:
  copy:
    name: Pull Repository on Server
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        # with:
        #   since_last_remote_commit: true
        #   separator: ","
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was changed"
          done

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          # source: .
          target: ${{ secrets.LOCAL_PATH }}
  deploy:
    needs: copy
    runs-on: ubuntu-20.04
    name: Deploy Docker Containers
    steps:
      # - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@v0.1.5
        name: remote docker-compose up via ssh
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          # envs: APPTOKEN,USERNAME
          script: |
            cd ${{ secrets.LOCAL_PATH }}
            docker compose -f ./backend/docker-compose.prod.yml down
            docker compose -f ./backend/docker-compose.prod.yml up -d --build
